server:
  port: 8585

spring:
  application:
    name: paperStock-backend
  data:
    mongodb:
      uri: mongodb://localhost:27017/paperstock
  graphql:
    path: /graphql

app:
  jwt:
    secret: papertrading-super-secret-key-papertrading-super-secret-key-1234567890
    expiration-ms: 86400000
