server:
  port: 8080

spring:
  application:
    name: paperStock-backend
  data:
    mongodb:
      uri: mongodb://localhost:27017/papertrading
    redis:
      host: localhost
      port: 6379
  cache:
    type: redis
  graphql:
    path: /graphql
    graphiql:
      enabled: true

app:
  jwt:
    secret: papertrading-super-secret-key-papertrading-super-secret-key-1234567890
    expiration-ms: 86400000
